# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tcnsn0IrF9Pb_AruwbwMjuBP59MJNP-A
"""

!pip install tensorflow

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator, load_img, img_to_array
import matplotlib.pyplot as plt
from google.colab import files



from google.colab import files

# This will prompt you to select files to upload
uploaded = files.upload()

image_path = 'WhatsApp Image 2024-02-11 at 16.45.10.jpeg'  # Make sure the name matches your uploaded image
img = load_img(image_path, target_size=(150, 150))  # Resize to match model input size

# Convert the image to an array and normalize
img_array = img_to_array(img) / 255.0  # Normalize the image
img_array = img_array.reshape((1, 150, 150, 3))

from tensorflow.keras.models import load_model

# Load your pre-trained model (replace 'your_model.h5' with your model file)
model = load_model('your_model.h5')

import os

# List files in the current directory
os.listdir()

from tensorflow.keras.models import load_model

# Replace 'your_model.h5' with the actual name of the uploaded file
model = load_model('WhatsApp Image 2024-02-11 at 16.45.10.h5')  # Update with your model file name

# Example: Define and compile your model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(150, 150, 3)),
    MaxPooling2D(),
    Flatten(),
    Dense(64, activation='relu'),
    Dense(num_classes, activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train your model
model.fit(train_generator, validation_data=validation_generator, epochs=10)

model.save('your_model.h5')