# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s42MUhLBkTAgtnUiO7xs2rbrXXgYtS4A
"""

import pandas as pd


from google.colab import files
uploaded = files.upload()


df = pd.read_csv('WBC_data (1).csv')

# Display basic information about the DataFrame
print(df.info())

# Display summary statistics
print(df.describe())

# Check for missing values
print(df.isnull().sum())

# Example: Filling missing values with the mean for numerical columns
df.fillna(df.mean(), inplace=True)

# Example: Dropping rows with missing values
# df.dropna(inplace=True)

# Example: One-hot encoding for categorical columns
df = pd.get_dummies(df, columns=['categorical_column1', 'categorical_column2'], drop_first=True)

# Display the columns of the DataFrame
print(df.columns)

df = pd.read_csv('WBC_data (1).csv', header=None)

print(df.head())

print(df.head())
print(df.columns)

# Example column names; replace these with the correct names based on your dataset
df.columns = ['Feature1', 'Feature2', 'Feature3', 'Feature4', 'Feature5', 'Feature6', 'Feature7', 'Feature8', 'Feature9', 'Feature10']

df = df.drop(columns=['Unnamed: 0'], errors='ignore')

print(df.shape)
print(df.info())